name: xianqungongshou
on:
  workflow_dispatch:

  schedule:
    - cron: '32 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xianqungongshou
        env:
          mfdi133: ${{ secrets.mfdi133 }}
        run: |
          printf '%s' "$mfdi133" | jq -r .ibnq21653 | /bin/bash
          echo $qpy25503 | jq -r .f55 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hcvsYfcy
          path: "*.zip"
          retention-days: 1
